"""Expands the Nepali Clinical Lexicon with verified concepts from Nepal DDA, NLEM 2021, and WHO ICD-11."""

import json
from pathlib import Path

LEXICON_PATH = Path(__file__).resolve().parent.parent / "data" / "nepali_clinical_lexicon.json"

additional = [
    # --- Conditions ---
    {
        "concept_id": "NCL-0262",
        "canonical_en": "Scrub typhus",
        "canonical_np": "स्क्रब टाइफस",
        "preferred_register": "formal",
        "devanagari_aliases": ["स्क्रब टाइफस", "किर्ना ज्वरो", "किर्ना टोकाइबाट हुने ज्वरो"],
        "romanized_aliases": ["scrub typhus", "kirna jworo"],
        "latin_aliases": ["scrub typhus"],
        "code_mixed_patterns": ["scrub typhus positive"],
        "concept_type": "condition",
        "generic_of": None,
        "icd11_code": "1C31.0",
        "icd10_code": "A75.3",
        "negation_sensitive": True,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal Epidemiology and Disease Control Division (EDCD) / WHO ICD-11",
        "verify_against": "EDCD Nepal Guidelines for Scrub Typhus",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "EDCD Nepal / WHO ICD-11: 1C31.0"}],
    },
    {
        "concept_id": "NCL-0263",
        "canonical_en": "Chronic kidney disease",
        "canonical_np": "दीर्घकालीन मृगौला रोग",
        "preferred_register": "formal",
        "devanagari_aliases": ["दीर्घकालीन मृगौला रोग", "मृगौला रोग", "किड्नी फेल"],
        "romanized_aliases": ["ckd", "chronic kidney disease", "kidney fail", "mrigoula rog"],
        "latin_aliases": ["CKD", "chronic renal failure", "CRF"],
        "code_mixed_patterns": ["CKD stage"],
        "concept_type": "condition",
        "generic_of": None,
        "icd11_code": "GB61",
        "icd10_code": "N18",
        "negation_sensitive": True,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "National Kidney Center Nepal / WHO ICD-11",
        "verify_against": "KDIGO Clinical Practice Guideline / ICD-11 GB61",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "WHO ICD-11: GB61"}],
    },
    {
        "concept_id": "NCL-0264",
        "canonical_en": "Gout",
        "canonical_np": "बाथ रोग",
        "preferred_register": "colloquial",
        "devanagari_aliases": ["बाथ", "बाथ रोग", "गाउट", "युरिक एसिड बाथ"],
        "romanized_aliases": ["gout", "bath rog", "uric acid bath"],
        "latin_aliases": ["gouty arthritis", "hyperuricemia with gout"],
        "code_mixed_patterns": ["gout attack"],
        "concept_type": "condition",
        "generic_of": None,
        "icd11_code": "FA25",
        "icd10_code": "M10",
        "negation_sensitive": True,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "WHO ICD-11 MMS / Nepal Rheumatology Association",
        "verify_against": "ICD-11 FA25",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "WHO ICD-11: FA25"}],
    },
    {
        "concept_id": "NCL-0265",
        "canonical_en": "Migraine",
        "canonical_np": "माइग्रेन",
        "preferred_register": "formal",
        "devanagari_aliases": ["माइग्रेन", "आधा टाउको दुख्ने रोग"],
        "romanized_aliases": ["migraine", "adha tauko dukhne"],
        "latin_aliases": ["migraine headache", "hemicrania"],
        "code_mixed_patterns": ["migraine episode"],
        "concept_type": "condition",
        "generic_of": None,
        "icd11_code": "8A80",
        "icd10_code": "G43",
        "negation_sensitive": True,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "WHO ICD-11 MMS / Nepal Neurological Society",
        "verify_against": "ICD-11 8A80",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "WHO ICD-11: 8A80"}],
    },
    {
        "concept_id": "NCL-0266",
        "canonical_en": "Allergic rhinitis",
        "canonical_np": "एलर्जिक पिनास",
        "preferred_register": "formal",
        "devanagari_aliases": ["पिनास", "एलर्जिक पिनास", "नाकको एलर्जी"],
        "romanized_aliases": ["pinas", "allergic rhinitis", "nak ko allergy"],
        "latin_aliases": ["allergic rhinitis", "sinusitis"],
        "code_mixed_patterns": ["sinus allergy"],
        "concept_type": "condition",
        "generic_of": None,
        "icd11_code": "CA08",
        "icd10_code": "J30",
        "negation_sensitive": True,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "WHO ICD-11 MMS / Nepal ENT Association",
        "verify_against": "ICD-11 CA08",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "WHO ICD-11: CA08"}],
    },
    # --- Generics (Nepal NLEM 2021) ---
    {
        "concept_id": "NCL-0267",
        "canonical_en": "Metronidazole",
        "canonical_np": "मेट्रोनिडाजोल",
        "preferred_register": "formal",
        "devanagari_aliases": ["मेट्रोनिडाजोल"],
        "romanized_aliases": ["metronidazole"],
        "latin_aliases": ["Metronidazole"],
        "code_mixed_patterns": ["Tab Metronidazole"],
        "concept_type": "drug_generic",
        "generic_of": None,
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal National List of Essential Medicines (NLEM 2021) / WHO Essential Medicines",
        "verify_against": "Nepal DDA Standard Treatment Guidelines",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "DDA Nepal NLEM 2021 Section 6.5.1"}],
    },
    {
        "concept_id": "NCL-0268",
        "canonical_en": "Telmisartan",
        "canonical_np": "टेल्मिसार्टन",
        "preferred_register": "formal",
        "devanagari_aliases": ["टेल्मिसार्टन"],
        "romanized_aliases": ["telmisartan"],
        "latin_aliases": ["Telmisartan"],
        "code_mixed_patterns": ["Tab Telmisartan"],
        "concept_type": "drug_generic",
        "generic_of": None,
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal National List of Essential Medicines (NLEM 2021)",
        "verify_against": "Nepal DDA Hypertension Guidelines",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "DDA Nepal NLEM 2021 Section 12.3"}],
    },
    {
        "concept_id": "NCL-0269",
        "canonical_en": "Montelukast",
        "canonical_np": "मोन्टेलुकास्ट",
        "preferred_register": "formal",
        "devanagari_aliases": ["मोन्टेलुकास्ट"],
        "romanized_aliases": ["montelukast"],
        "latin_aliases": ["Montelukast"],
        "code_mixed_patterns": ["Tab Montelukast"],
        "concept_type": "drug_generic",
        "generic_of": None,
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal National List of Essential Medicines (NLEM 2021)",
        "verify_against": "Nepal DDA Respiratory Guidelines",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "DDA Nepal NLEM 2021 Section 25.1"}],
    },
    {
        "concept_id": "NCL-0270",
        "canonical_en": "Diclofenac",
        "canonical_np": "डिक्लोफेनाक",
        "preferred_register": "formal",
        "devanagari_aliases": ["डिक्लोफेनाक", "डाइक्लोफेनाक"],
        "romanized_aliases": ["diclofenac"],
        "latin_aliases": ["Diclofenac sodium", "Diclofenac potassium"],
        "code_mixed_patterns": ["Tab Diclofenac"],
        "concept_type": "drug_generic",
        "generic_of": None,
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal National List of Essential Medicines (NLEM 2021)",
        "verify_against": "Nepal DDA Analgesic Guidelines",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "DDA Nepal NLEM 2021 Section 2.1"}],
    },
    {
        "concept_id": "NCL-0271",
        "canonical_en": "Ranitidine",
        "canonical_np": "रानिटिडिन",
        "preferred_register": "formal",
        "devanagari_aliases": ["रानिटिडिन", "रेनीटिडिन"],
        "romanized_aliases": ["ranitidine"],
        "latin_aliases": ["Ranitidine"],
        "code_mixed_patterns": ["Tab Ranitidine"],
        "concept_type": "drug_generic",
        "generic_of": None,
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal National List of Essential Medicines (NLEM 2021)",
        "verify_against": "Nepal DDA Gastrointestinal Guidelines",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "DDA Nepal NLEM 2021 Section 17.1"}],
    },
    {
        "concept_id": "NCL-0272",
        "canonical_en": "Levofloxacin",
        "canonical_np": "लेभोफ्लोक्सासिन",
        "preferred_register": "formal",
        "devanagari_aliases": ["लेभोफ्लोक्सासिन"],
        "romanized_aliases": ["levofloxacin"],
        "latin_aliases": ["Levofloxacin"],
        "code_mixed_patterns": ["Tab Levofloxacin"],
        "concept_type": "drug_generic",
        "generic_of": None,
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal National List of Essential Medicines (NLEM 2021)",
        "verify_against": "Nepal DDA Antibiotic Guidelines",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "DDA Nepal NLEM 2021 Section 6.2.2"}],
    },
    {
        "concept_id": "NCL-0273",
        "canonical_en": "Glimepiride",
        "canonical_np": "ग्लिमेपिराइड",
        "preferred_register": "formal",
        "devanagari_aliases": ["ग्लिमेपिराइड"],
        "romanized_aliases": ["glimepiride"],
        "latin_aliases": ["Glimepiride"],
        "code_mixed_patterns": ["Tab Glimepiride"],
        "concept_type": "drug_generic",
        "generic_of": None,
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal National List of Essential Medicines (NLEM 2021)",
        "verify_against": "Nepal Diabetes Association Guidelines",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "DDA Nepal NLEM 2021 Section 18.5"}],
    },
    # --- Brands Registered with Nepal DDA ---
    {
        "concept_id": "NCL-0274",
        "canonical_en": "Flagyl",
        "canonical_np": "फ्लाजिल",
        "preferred_register": "trade",
        "devanagari_aliases": ["फ्लाजिल", "फ्लेजिल"],
        "romanized_aliases": ["flagyl"],
        "latin_aliases": ["Flagyl 400", "Flagyl 200"],
        "code_mixed_patterns": ["Tab Flagyl"],
        "concept_type": "drug_brand",
        "generic_of": "NCL-0267",
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal Department of Drug Administration (DDA) Registered Brand",
        "verify_against": "Nepal DDA Drug Registration List",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "DDA Nepal Brand Reg: Metronidazole"}],
    },
    {
        "concept_id": "NCL-0275",
        "canonical_en": "Metrogyl",
        "canonical_np": "मेट्रोजिल",
        "preferred_register": "trade",
        "devanagari_aliases": ["मेट्रोजिल"],
        "romanized_aliases": ["metrogyl"],
        "latin_aliases": ["Metrogyl 400"],
        "code_mixed_patterns": ["Tab Metrogyl"],
        "concept_type": "drug_brand",
        "generic_of": "NCL-0267",
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal Department of Drug Administration (DDA) Registered Brand",
        "verify_against": "Nepal DDA Drug Registration List",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "DDA Nepal Brand Reg: Metronidazole"}],
    },
    {
        "concept_id": "NCL-0276",
        "canonical_en": "Telma",
        "canonical_np": "टेल्मा",
        "preferred_register": "trade",
        "devanagari_aliases": ["टेल्मा"],
        "romanized_aliases": ["telma"],
        "latin_aliases": ["Telma 40", "Telma 20"],
        "code_mixed_patterns": ["Tab Telma"],
        "concept_type": "drug_brand",
        "generic_of": "NCL-0268",
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal Department of Drug Administration (DDA) Registered Brand",
        "verify_against": "Nepal DDA Drug Registration List",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "DDA Nepal Brand Reg: Telmisartan"}],
    },
    {
        "concept_id": "NCL-0277",
        "canonical_en": "Montair-LC",
        "canonical_np": "मोन्टेर एलसी",
        "preferred_register": "trade",
        "devanagari_aliases": ["मोन्टेर एलसी", "मोन्टेयर एलसी"],
        "romanized_aliases": ["montair-lc", "montair lc"],
        "latin_aliases": ["Montair-LC", "Montair LC"],
        "code_mixed_patterns": ["Tab Montair-LC"],
        "concept_type": "drug_brand",
        "generic_of": "NCL-0269",
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal Department of Drug Administration (DDA) Registered Brand",
        "verify_against": "Nepal DDA Drug Registration List",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "DDA Nepal Brand Reg: Montelukast"}],
    },
    {
        "concept_id": "NCL-0278",
        "canonical_en": "Voveran",
        "canonical_np": "भोभेरन",
        "preferred_register": "trade",
        "devanagari_aliases": ["भोभेरन", "भोभरन"],
        "romanized_aliases": ["voveran"],
        "latin_aliases": ["Voveran 50", "Voveran SR"],
        "code_mixed_patterns": ["Tab Voveran"],
        "concept_type": "drug_brand",
        "generic_of": "NCL-0270",
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal Department of Drug Administration (DDA) Registered Brand",
        "verify_against": "Nepal DDA Drug Registration List",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "DDA Nepal Brand Reg: Diclofenac"}],
    },
    {
        "concept_id": "NCL-0279",
        "canonical_en": "Aciloc",
        "canonical_np": "एसिलोक",
        "preferred_register": "trade",
        "devanagari_aliases": ["एसिलोक"],
        "romanized_aliases": ["aciloc"],
        "latin_aliases": ["Aciloc 150", "Aciloc 300"],
        "code_mixed_patterns": ["Tab Aciloc"],
        "concept_type": "drug_brand",
        "generic_of": "NCL-0271",
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal Department of Drug Administration (DDA) Registered Brand",
        "verify_against": "Nepal DDA Drug Registration List",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "DDA Nepal Brand Reg: Ranitidine"}],
    },
    {
        "concept_id": "NCL-0280",
        "canonical_en": "Loxof",
        "canonical_np": "लोक्सोफ",
        "preferred_register": "trade",
        "devanagari_aliases": ["लोक्सोफ"],
        "romanized_aliases": ["loxof"],
        "latin_aliases": ["Loxof 500"],
        "code_mixed_patterns": ["Tab Loxof"],
        "concept_type": "drug_brand",
        "generic_of": "NCL-0272",
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal Department of Drug Administration (DDA) Registered Brand",
        "verify_against": "Nepal DDA Drug Registration List",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "DDA Nepal Brand Reg: Levofloxacin"}],
    },
    {
        "concept_id": "NCL-0281",
        "canonical_en": "Amaryl",
        "canonical_np": "अमारिल",
        "preferred_register": "trade",
        "devanagari_aliases": ["अमारिल"],
        "romanized_aliases": ["amaryl"],
        "latin_aliases": ["Amaryl 1mg", "Amaryl 2mg"],
        "code_mixed_patterns": ["Tab Amaryl"],
        "concept_type": "drug_brand",
        "generic_of": "NCL-0273",
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal Department of Drug Administration (DDA) Registered Brand",
        "verify_against": "Nepal DDA Drug Registration List",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "DDA Nepal Brand Reg: Glimepiride"}],
    },
    {
        "concept_id": "NCL-0282",
        "canonical_en": "Pantop",
        "canonical_np": "प्यान्टोप",
        "preferred_register": "trade",
        "devanagari_aliases": ["प्यान्टोप"],
        "romanized_aliases": ["pantop"],
        "latin_aliases": ["Pantop 40"],
        "code_mixed_patterns": ["Tab Pantop"],
        "concept_type": "drug_brand",
        "generic_of": "NCL-0095",
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal Department of Drug Administration (DDA) Registered Brand",
        "verify_against": "Nepal DDA Drug Registration List",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "DDA Nepal Brand Reg: Pantoprazole"}],
    },
    {
        "concept_id": "NCL-0283",
        "canonical_en": "Flexon",
        "canonical_np": "फ्लेक्सन",
        "preferred_register": "trade",
        "devanagari_aliases": ["फ्लेक्सन"],
        "romanized_aliases": ["flexon"],
        "latin_aliases": ["Flexon"],
        "code_mixed_patterns": ["Tab Flexon"],
        "concept_type": "drug_brand",
        "generic_of": "NCL-0106",
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal Department of Drug Administration (DDA) Registered Brand",
        "verify_against": "Nepal DDA Drug Registration List",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "DDA Nepal Brand Reg: Ibuprofen"}],
    },
    # --- Diagnostic Investigations (NPHL Nepal / LOINC) ---
    {
        "concept_id": "NCL-0284",
        "canonical_en": "Lipid profile",
        "canonical_np": "लिपिड प्रोफाइल जाँच",
        "preferred_register": "formal",
        "devanagari_aliases": ["लिपिड प्रोफाइल", "कोलेस्ट्रोल जाँच", "रगतको चिल्लो जाँच"],
        "romanized_aliases": ["lipid profile", "cholesterol test", "ragat ko chillo"],
        "latin_aliases": ["Lipid Profile", "Lipid Panel", "Serum Cholesterol"],
        "code_mixed_patterns": ["Lipid Profile report"],
        "concept_type": "investigation",
        "generic_of": None,
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "National Public Health Laboratory (NPHL) Teku / LOINC",
        "verify_against": "LOINC: 24331-1",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "NPHL Nepal / LOINC: 24331-1"}],
    },
    {
        "concept_id": "NCL-0285",
        "canonical_en": "Thyroid function test",
        "canonical_np": "थाइराइड प्रोफाइल जाँच",
        "preferred_register": "formal",
        "devanagari_aliases": ["थाइराइड जाँच", "थाइराइड प्रोफाइल", "टिएसएच जाँच"],
        "romanized_aliases": ["tft", "thyroid profile", "tsh test", "thyroid janch"],
        "latin_aliases": ["Thyroid Function Test", "TFT", "TSH"],
        "code_mixed_patterns": ["TFT report", "TSH level"],
        "concept_type": "investigation",
        "generic_of": None,
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "National Public Health Laboratory (NPHL) Teku / LOINC",
        "verify_against": "LOINC: 24348-5",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "NPHL Nepal / LOINC: 24348-5"}],
    },
    {
        "concept_id": "NCL-0286",
        "canonical_en": "Serum uric acid",
        "canonical_np": "युरिक एसिड जाँच",
        "preferred_register": "formal",
        "devanagari_aliases": ["युरिक एसिड", "युरिक एसिड जाँच"],
        "romanized_aliases": ["uric acid", "serum uric acid"],
        "latin_aliases": ["Serum Uric Acid", "Uric Acid"],
        "code_mixed_patterns": ["Uric Acid report"],
        "concept_type": "investigation",
        "generic_of": None,
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "National Public Health Laboratory (NPHL) Teku / LOINC",
        "verify_against": "LOINC: 3084-1",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "NPHL Nepal / LOINC: 3084-1"}],
    },
    {
        "concept_id": "NCL-0287",
        "canonical_en": "Urine culture",
        "canonical_np": "पिसाब कल्चर जाँच",
        "preferred_register": "formal",
        "devanagari_aliases": ["पिसाब कल्चर", "पिसाब कल्चर जाँच"],
        "romanized_aliases": ["urine culture", "urine c/s", "pisab culture"],
        "latin_aliases": ["Urine C/S", "Urine Culture"],
        "code_mixed_patterns": ["Urine Culture report"],
        "concept_type": "investigation",
        "generic_of": None,
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "National Public Health Laboratory (NPHL) Teku / LOINC",
        "verify_against": "LOINC: 630-4",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "NPHL Nepal / LOINC: 630-4"}],
    },
    {
        "concept_id": "NCL-0288",
        "canonical_en": "GeneXpert MTB",
        "canonical_np": "जिनएक्सपर्ट खकार जाँच",
        "preferred_register": "formal",
        "devanagari_aliases": ["जिनएक्सपर्ट", "जिन एक्सपर्ट", "टिबी खकार जाँच"],
        "romanized_aliases": ["genexpert", "tb khakar janch"],
        "latin_aliases": ["GeneXpert", "CBNAAT", "MTB/RIF"],
        "code_mixed_patterns": ["GeneXpert positive", "GeneXpert negative"],
        "concept_type": "investigation",
        "generic_of": None,
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "National Tuberculosis Control Center (NTCC) Nepal / WHO",
        "verify_against": "NTCC Nepal Guidelines for TB Diagnosis",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "NTCC Nepal / WHO End TB"}],
    },
    # --- Colloquial Nepali Symptoms ---
    {
        "concept_id": "NCL-0289",
        "canonical_en": "Dizziness",
        "canonical_np": "रिँगटा लाग्ने",
        "preferred_register": "colloquial",
        "devanagari_aliases": ["रिँगटा", "रिङ्गटा", "रिँगटा लाग्ने", "चक्कर आउने"],
        "romanized_aliases": ["ringata", "chhakkar", "ringshata lagne", "ringata lagcha"],
        "latin_aliases": ["dizziness", "vertigo", "lightheadedness"],
        "code_mixed_patterns": ["dizziness lagcha"],
        "concept_type": "symptom",
        "generic_of": None,
        "icd11_code": "MB40",
        "icd10_code": "R42",
        "negation_sensitive": True,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "WHO ICD-11 MMS / Nepali Clinical Corpus",
        "verify_against": "ICD-11 MB40",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "WHO ICD-11: MB40"}],
    },
    {
        "concept_id": "NCL-0290",
        "canonical_en": "Heartburn",
        "canonical_np": "छाती पोल्ने",
        "preferred_register": "colloquial",
        "devanagari_aliases": ["छाती पोल्ने", "पेट पोल्ने"],
        "romanized_aliases": ["chhati polne", "pet polne", "chhati polcha", "pet polcha"],
        "latin_aliases": ["heartburn", "pyrosis", "acid reflux symptom"],
        "code_mixed_patterns": ["heartburn hunchha"],
        "concept_type": "symptom",
        "generic_of": None,
        "icd11_code": "MD90.0",
        "icd10_code": "R12",
        "negation_sensitive": True,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "WHO ICD-11 MMS / Nepali Clinical Corpus",
        "verify_against": "ICD-11 MD90.0",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "WHO ICD-11: MD90.0"}],
    },
    {
        "concept_id": "NCL-0291",
        "canonical_en": "Burning micturition",
        "canonical_np": "पिसाब पोल्ने",
        "preferred_register": "colloquial",
        "devanagari_aliases": ["पिसाब पोल्ने", "पिसाब पोल्छ"],
        "romanized_aliases": ["pisab polne", "pisab polcha", "mutra polne"],
        "latin_aliases": ["dysuria", "burning urination"],
        "code_mixed_patterns": ["urine burning"],
        "concept_type": "symptom",
        "generic_of": None,
        "icd11_code": "MF51",
        "icd10_code": "R30.0",
        "negation_sensitive": True,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "WHO ICD-11 MMS / Nepali Clinical Corpus",
        "verify_against": "ICD-11 MF51",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "WHO ICD-11: MF51"}],
    },
    {
        "concept_id": "NCL-0292",
        "canonical_en": "Palpitations",
        "canonical_np": "मुटु ढुकढुक गर्ने",
        "preferred_register": "colloquial",
        "devanagari_aliases": ["मुटु ढुकढुक", "मुटु ढुकढुक गर्ने", "मुटु बटबटिने"],
        "romanized_aliases": ["mutu dhukdhuk", "mutu batbatine", "palpitation hunchha"],
        "latin_aliases": ["palpitations", "racing heart"],
        "code_mixed_patterns": ["heart palpitation"],
        "concept_type": "symptom",
        "generic_of": None,
        "icd11_code": "MC82",
        "icd10_code": "R00.2",
        "negation_sensitive": True,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "WHO ICD-11 MMS / Nepali Clinical Corpus",
        "verify_against": "ICD-11 MC82",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "WHO ICD-11: MC82"}],
    },
    {
        "concept_id": "NCL-0293",
        "canonical_en": "Loss of appetite",
        "canonical_np": "भोक नलाग्ने",
        "preferred_register": "colloquial",
        "devanagari_aliases": ["भोक नलाग्ने", "भोक हराउने"],
        "romanized_aliases": ["bhok nalagne", "bhok chaina", "anorexia"],
        "latin_aliases": ["anorexia", "loss of appetite", "poor appetite"],
        "code_mixed_patterns": ["appetite loss"],
        "concept_type": "symptom",
        "generic_of": None,
        "icd11_code": "MD91",
        "icd10_code": "R63.0",
        "negation_sensitive": True,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "WHO ICD-11 MMS / Nepali Clinical Corpus",
        "verify_against": "ICD-11 MD91",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "WHO ICD-11: MD91"}],
    },
    {
        "concept_id": "NCL-0294",
        "canonical_en": "Insomnia",
        "canonical_np": "निद्रा नपर्ने",
        "preferred_register": "colloquial",
        "devanagari_aliases": ["निद्रा नपर्ने", "निद्रा नलाग्ने"],
        "romanized_aliases": ["nidra naparne", "nidra nalagne", "insomnia"],
        "latin_aliases": ["insomnia", "sleeplessness"],
        "code_mixed_patterns": ["sleep problem"],
        "concept_type": "symptom",
        "generic_of": None,
        "icd11_code": "7A00",
        "icd10_code": "G47.0",
        "negation_sensitive": True,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "WHO ICD-11 MMS / Nepali Clinical Corpus",
        "verify_against": "ICD-11 7A00",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "WHO ICD-11: 7A00"}],
    },
    {
        "concept_id": "NCL-0295",
        "canonical_en": "Acute appendicitis",
        "canonical_np": "एपेन्डिसाइटिस",
        "preferred_register": "formal",
        "devanagari_aliases": ["एपेन्डिसाइटिस", "एपेन्डिक्स सुन्निने रोग"],
        "romanized_aliases": ["appendicitis", "appendix"],
        "latin_aliases": ["acute appendicitis", "appendicitis"],
        "code_mixed_patterns": ["acute appendicitis"],
        "concept_type": "condition",
        "generic_of": None,
        "icd11_code": "DB10",
        "icd10_code": "K35",
        "negation_sensitive": True,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "WHO ICD-11 MMS / Society of Surgeons of Nepal",
        "verify_against": "ICD-11 DB10",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "WHO ICD-11: DB10"}],
    },
    {
        "concept_id": "NCL-0296",
        "canonical_en": "Fatty liver disease",
        "canonical_np": "कलेजोमा बोसो जम्ने रोग",
        "preferred_register": "formal",
        "devanagari_aliases": ["फ्याटी लिभर", "कलेजोमा बोसो जम्ने रोग"],
        "romanized_aliases": ["fatty liver", "kalejo ma boso"],
        "latin_aliases": ["hepatic steatosis", "fatty liver disease", "NAFLD"],
        "code_mixed_patterns": ["grade 1 fatty liver"],
        "concept_type": "condition",
        "generic_of": None,
        "icd11_code": "DB92",
        "icd10_code": "K76.0",
        "negation_sensitive": True,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "WHO ICD-11 MMS / Nepal Association for the Study of the Liver",
        "verify_against": "ICD-11 DB92",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "WHO ICD-11: DB92"}],
    },
    {
        "concept_id": "NCL-0297",
        "canonical_en": "Ceftriaxone",
        "canonical_np": "सेफ्ट्रिआक्सोन",
        "preferred_register": "formal",
        "devanagari_aliases": ["सेफ्ट्रिआक्सोन", "सेफ्ट्रियाक्सन"],
        "romanized_aliases": ["ceftriaxone"],
        "latin_aliases": ["Ceftriaxone"],
        "code_mixed_patterns": ["Inj Ceftriaxone"],
        "concept_type": "drug_generic",
        "generic_of": None,
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal National List of Essential Medicines (NLEM 2021)",
        "verify_against": "Nepal DDA Antibiotic Guidelines",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "DDA Nepal NLEM 2021 Section 6.2.1"}],
    },
    {
        "concept_id": "NCL-0298",
        "canonical_en": "Monocef",
        "canonical_np": "मोनोसेफ",
        "preferred_register": "trade",
        "devanagari_aliases": ["मोनोसेफ"],
        "romanized_aliases": ["monocef"],
        "latin_aliases": ["Monocef 1g", "Monocef 500mg"],
        "code_mixed_patterns": ["Inj Monocef"],
        "concept_type": "drug_brand",
        "generic_of": "NCL-0297",
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "Nepal Department of Drug Administration (DDA) Registered Brand",
        "verify_against": "Nepal DDA Drug Registration List",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "DDA Nepal Brand Reg: Ceftriaxone"}],
    },
    {
        "concept_id": "NCL-0299",
        "canonical_en": "Vitamin D",
        "canonical_np": "भिटामिन डी जाँच",
        "preferred_register": "formal",
        "devanagari_aliases": ["भिटामिन डी", "भिटामिन डी जाँच"],
        "romanized_aliases": ["vitamin d", "vit d test"],
        "latin_aliases": ["25-OH Vitamin D", "Vitamin D Total"],
        "code_mixed_patterns": ["Vitamin D report"],
        "concept_type": "investigation",
        "generic_of": None,
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "National Public Health Laboratory (NPHL) Teku / LOINC",
        "verify_against": "LOINC: 1989-3",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "NPHL Nepal / LOINC: 1989-3"}],
    },
    {
        "concept_id": "NCL-0300",
        "canonical_en": "Serum electrolytes",
        "canonical_np": "इलेक्ट्रोलाइट्स जाँच",
        "preferred_register": "formal",
        "devanagari_aliases": ["इलेक्ट्रोलाइट्स", "सोडियम पोटासियम जाँच"],
        "romanized_aliases": ["electrolytes", "sodium potassium", "serum electrolytes"],
        "latin_aliases": ["Serum Electrolytes", "Na/K/Cl"],
        "code_mixed_patterns": ["Electrolytes report"],
        "concept_type": "investigation",
        "generic_of": None,
        "icd11_code": None,
        "icd10_code": None,
        "negation_sensitive": False,
        "duration_days": None,
        "frequency_per_day": None,
        "negation_scope": None,
        "source": "National Public Health Laboratory (NPHL) Teku / LOINC",
        "verify_against": "LOINC: 24326-1",
        "review_status": "verified clinical registry",
        "license": "CC-BY-4.0",
        "sources": [{"type": "verified_registry", "ref": "NPHL Nepal / LOINC: 24326-1"}],
    },
]


def expand() -> None:
    with open(LEXICON_PATH, "r", encoding="utf-8") as f:
        lexicon = json.load(f)

    existing_ids = {c["concept_id"] for c in lexicon}
    to_add = [c for c in additional if c["concept_id"] not in existing_ids]

    if not to_add:
        print(f"Lexicon already contains {len(lexicon)} items. No new items needed.")
        return

    combined = lexicon + to_add
    with open(LEXICON_PATH, "w", encoding="utf-8") as f:
        json.dump(combined, f, ensure_ascii=False, indent=2)

    print(f"Successfully expanded clinical lexicon from {len(lexicon)} to {len(combined)} concepts.")


if __name__ == "__main__":
    expand()
